[0m[[0m[31merror[0m] [0m[0mC:\Users\Magician\Documents\Github\S-99-Ninety-Nine-Scala-Problems\20.scala:8:8: test_16 is already defined as object test_16[0m
[0m[[0m[31merror[0m] [0m[0mobject test_16{[0m
[0m[[0m[31merror[0m] [0m[0m       ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
